from model import SmileInModel as TheModel
from model import FaceNet as TheFaceNet
from model import SmileNet as TheSmileNet
from train import train_model as the_trainer
from predict import predict_attendance as the_predictor
from predict import predict_identity as the_identity_predictor
from predict import predict_smile as the_smile_predictor
from dataset import FaceIdentityDataset as TheDataset
from dataset import SmileDataset as TheSmileDataset
from dataset import get_face_dataloader as the_dataloader
from dataset import get_smile_dataloader as the_smile_dataloader
from config import face_batch_size as the_batch_size
from config import face_epochs as total_epochs
from config import smile_batch_size as the_smile_batch_size
from config import smile_epochs as total_smile_epochs